on:
  push:
    branches:
    - main

jobs:
  BuildAndDeploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4.3.1
      - name: Install
        run: python3 -m pip 
      - name: Build
        run: python3 -m pip  install -r requirements.txt       
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.3
        with:
          artifact_name: public
